/* Run with NODE_PATH pointing to linkedom, e.g. npm install linkedom in test environment. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const { parseHTML } = require('linkedom');
const html = fs.readFileSync(process.env.RENDERED_HTML || '/tmp/es-home.html', 'utf8');
const { document } = parseHTML(html);
const window = { scrollY: 0, addEventListener: () => {} };
const context = vm.createContext({ document, window, console });
vm.runInContext(fs.readFileSync('my-custom-theme/assets/js/theme.js', 'utf8'), context);
const toggle = document.querySelector('.menu-toggle');
const nav = document.getElementById('primary-nav');
toggle.click();
assert.equal(toggle.getAttribute('aria-expanded'), 'true');
assert.ok(nav.classList.contains('is-open'));
toggle.click();
assert.equal(toggle.getAttribute('aria-expanded'), 'false');
const button = document.querySelector('[data-service="2"]');
button.click();
assert.ok(button.classList.contains('is-active'));
assert.equal(button.getAttribute('aria-pressed'), 'true');
assert.equal(document.getElementById('service-title').textContent, 'نورپردازی پل');
assert.ok(document.getElementById('service-image').getAttribute('src').includes('light-tunnel.jpg'));
console.log('PASS: navigation and interactive service panel');
const adminDOM = parseHTML(`<div class="es-repeater" data-repeater data-key="stats"><div data-repeater-rows></div><button data-add-row type="button">افزودن</button><template data-row-template><div class="es-repeat-row"><input name="es_options[stats][__INDEX__][label]"><button data-remove-row type="button">حذف</button></div></template></div><div data-faq-rows></div><button data-add-faq type="button">افزودن سؤال</button>`);
const adminDocument = adminDOM.document;
const adminContext = vm.createContext({ document: adminDocument, window: {}, console });
vm.runInContext(fs.readFileSync('my-custom-theme/assets/js/admin.js', 'utf8'), adminContext);
adminDocument.querySelector('[data-add-row]').click();
assert.equal(adminDocument.querySelectorAll('[data-repeater-rows] .es-repeat-row').length, 1);
assert.ok(!adminDocument.querySelector('[data-repeater-rows] input').name.includes('__INDEX__'));
adminDocument.querySelector('[data-remove-row]').click();
assert.equal(adminDocument.querySelectorAll('[data-repeater-rows] .es-repeat-row').length, 0);
adminDocument.querySelector('[data-add-faq]').click();
assert.equal(adminDocument.querySelectorAll('[data-faq-rows] input').length, 2);
console.log('PASS: admin repeater and FAQ interactions');
