<?php
/** WooCommerce facsimile for browser snapshots only. */
function the_post() {}
function get_the_ID() { return 103; }
function is_product() { return (bool) getenv( 'ES_RENDER_PRODUCT' ); }
function get_the_terms( $id, $taxonomy ) { return array( (object) array( 'name' => 'درختان نوری هوشمند' ) ); }
function is_wp_error( $value ) { return false; }
function get_term_link( $term ) { return '/products/'; }
function get_post_meta( $id, $key, $single = false ) { if ( getenv( 'ES_RENDER_ONLINE' ) && '_es_order_type' === $key ) { return 'online_cart'; } if ( getenv( 'ES_RENDER_ONLINE' ) && '_es_is_purchasable_online' === $key ) { return '1'; } return array( '_es_order_type' => 'phone_inquiry', '_es_is_purchasable_online' => '0', '_es_custom_price_badge' => 'قیمت پس از بررسی پروژه', '_es_wattage_rating' => '۱۲۰', '_es_production_lead_time' => 'متناسب با سفارش' )[ $key ] ?? ''; }
function metadata_exists( $type, $id, $key ) { return true; }
class MockEsProduct { private $id; function __construct( $id ) { $this->id = $id; } function get_id() { return $this->id; } function get_name() { return $this->id === 103 ? 'درخت نوری هوشمند آرتام' : ( $this->id === 104 ? 'گوی نورانی شهری' : ( $this->id === 105 ? 'تونل نوری LED' : 'المان نوری شهری' ) ); } function get_image_id() { return $this->id; } function get_price_html() { return '۱٬۲۰۰٬۰۰۰ تومان'; } }
function wc_get_product( $id ) { return new MockEsProduct( $id ); }
function wc_get_products( $args ) { return array( new MockEsProduct( 104 ), new MockEsProduct( 105 ), new MockEsProduct( 106 ) ); }
function wc_get_related_products( $id, $limit ) { return array(); }
function wc_product_class( $classes, $product ) { echo 'class="product ' . esc_attr( $classes ) . '"'; }
function woocommerce_breadcrumb( $options ) { echo $options['wrap_before'] . '<a href="/">خانه</a>' . $options['delimiter'] . '<a href="/products/">محصولات</a>' . $options['delimiter'] . 'درخت نوری هوشمند آرتام' . $options['wrap_after']; }
function do_action( $hook ) { if ( 'woocommerce_before_single_product_summary' === $hook ) { echo '<div class="woocommerce-product-gallery"><figure class="woocommerce-product-gallery__wrapper"><div class="woocommerce-product-gallery__image"><a href="/my-custom-theme/assets/images/light-tree.jpg"><img src="/my-custom-theme/assets/images/light-tree.jpg" alt="درخت نوری هوشمند آرتام"></a></div></figure><ol class="flex-control-thumbs"><li><img src="/my-custom-theme/assets/images/light-tree.jpg" alt="نمای اصلی" class="flex-active"></li><li><img src="/my-custom-theme/assets/images/light-element.jpg" alt="جزئیات محصول"></li></ol></div>'; } if ( 'woocommerce_single_product_summary' === $hook ) { echo '<h1 class="product_title entry-title">درخت نوری هوشمند آرتام</h1><div class="woocommerce-product-details__short-description"><p>تلفیقی از هنر نورپردازی و مهندسی شهری؛ طراحی و تولید متناسب با فضای پروژه شما.</p></div>' . ( getenv( 'ES_RENDER_ONLINE' ) ? '<p class="price">۱٬۲۰۰٬۰۰۰ تومان</p><form class="cart" method="post"><div class="quantity"><input class="qty" type="number" name="quantity" value="1" min="1" aria-label="تعداد"></div><button class="single_add_to_cart_button button alt" type="submit" name="add-to-cart" value="103">افزودن به سبد خرید</button></form>' : '<p class="price"><span class="es-price-badge">استعلام قیمت</span></p><div class="es-inquiry"><p>قیمت پس از بررسی پروژه اعلام می‌شود.</p><a class="btn btn--gold" href="tel:03191091011">استعلام قیمت و مشاوره</a></div>' ) . '<div class="es-product-specs"><p><strong>توان نامی (وات)</strong><span>۱۲۰</span></p></div>'; } }
function woocommerce_output_product_data_tabs() { echo '<div class="woocommerce-tabs wc-tabs-wrapper"><ul class="tabs wc-tabs"><li class="description_tab active"><a href="#tab-description">توضیحات</a></li><li class="additional_information_tab"><a href="#tab-additional_information">مشخصات فنی</a></li><li class="reviews_tab"><a href="#tab-reviews">دیدگاه‌ها</a></li></ul><div class="woocommerce-Tabs-panel panel entry-content" id="tab-description"><h2>درخت نوری هوشمند آرتام</h2><p>درختان نوری برای فضاهای شهری با امکان طراحی متناسب با پروژه؛ برای دریافت مشخصات کامل با کارشناسان تماس بگیرید.</p></div></div>'; }
